include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - lib/firebase_options.dart
    - 'lib/**/*.g.dart'
    - 'lib/**/*.freezed.dart'

linter:

  rules:
